services:
  employment-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - employ-mysql-service
    #   - redis-container
    restart: always
    ports:
      - 3030:3030
    networks:
      - common-networks

  employ-mysql-service:
    image: mysql
    hostname: employ-mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: sens
      MYSQL_DATABASE: employment
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 3306:3306
    networks:
      - common-networks
    volumes:
      - /root/mysql-volumes:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro # 挂载主机的本地时间
  # redis-container:
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - common-networks
  #   volumes:
  #     - /root/redis-volumes/redis:/data

networks:
  common-networks:
    driver: bridge
